name: "MagicPodAction"
description: "Run MagicPod test"

# TODO: inputs, outputsを修正
inputs:
  ARG:
    description: "sample input"
    required: true

outputs:
  RES:
    description: "sample output"

runs:
  using: "node16"
  main: "dist/index.js"
